---
name: hq
synopsis: A streaming JSON processor inspired by jq, with a lens-based query language.
version: 0.0.0.1
author: damianfral
github: damianfral/hq
category: JSON, CLI, lenses, optics, streaming

license: MIT

extra-source-files:
  - docs/LANG.md

library:
  source-dirs: ./src/
  dependencies:
    - aeson
    - base
    - bytestring
    - file-embed
    - megaparsec
    - mtl
    - optparse-applicative
    - parser-combinators
    - relude
    - scientific
    - streaming
    - text
    - transformers
    - vector

ghc-options:
  - -O2
  - -fshow-warning-groups
  - -Werror
  - -Wall
  - -Wcompat
  - -Wcpp-undef
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fwrite-ide-info
  - -funbox-strict-fields
  - -flate-dmd-anal
  - -fno-omit-interface-pragmas
  - -fregs-graph
  - -fspec-constr-recursive=32
  - -fmax-worker-args=32

executables:
  hq:
    main: Main.hs
    source-dirs: ./app/
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-qg
    dependencies:
      - base
      - hq
      - optparse-applicative
      - relude

tests:
  hq-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - base
      - bytestring
      - hq
      - megaparsec
      - mtl
      - optparse-applicative
      - relude
      - scientific
      - streaming
      - sydtest
      - sydtest-discover
      - vector
