---
name: hq
synopsis: A streaming JSON processor inspired by jq, with a lens-based query language.
version: 0.0.0.1
author: damianfral
github: damianfral/hq
category: JSON, CLI, lenses, optics, streaming

license: MIT

extra-source-files:
  - docs/LANG.md

library:
  source-dirs: ./src/
  dependencies:
    - aeson
    - base
    - bytestring
    - file-embed
    - megaparsec
    - optparse-applicative
    - parser-combinators
    - relude
    - scientific
    - streaming
    - text
    - vector

ghc-options:
  - -O2
  - -fshow-warning-groups
  - -Werror
  - -Weverything
  - -Wno-error=unused-packages
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-export-lists
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-role-annotations
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-safe
  - -Wno-unsafe
  - -fwrite-ide-info
  - -funbox-strict-fields
  - -flate-dmd-anal
  - -fno-omit-interface-pragmas
  - -fregs-graph
  - -fspec-constr-recursive=32
  - -fmax-worker-args=32

executables:
  hq:
    main: Main.hs
    source-dirs: ./app/
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-qg
    dependencies:
      - base
      - hq
      - relude

tests:
  hq-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - base
      - hq
      - optparse-applicative
      - relude
      - scientific
      - streaming
      - sydtest
      - sydtest-discover
